Update build-miui
参考https://github.com/UtsavBalar1231/kernel_xiaomi_sm8250/blob/android12-stable/scripts/build_kernel

diff --git a/build-miui b/build-miui
--- a/build-miui
+++ b/build-miui
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2199
-# shellcheck disable=SC2086
 # shellcheck source=/dev/null
 #
 # Copyright (C) 2020-22 UtsavBalar1231 <utsavbalar1231@gmail.com>
@@ -16,20 +15,65 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#HOME="/opt/shiro"
-# Set current date
-DATE=$(date +"%d.%m.%y")
+
+# Start cleanup of previous build
+if [[ -d anykernel ]]; then
+	rm -fr $(pwd)/anykernel/
+fi
+
+if [[ -f ${OUT_DIR}/arch/arm64/boot/dtb ]]; then
+	rm -fr ${OUT_DIR}/arch/arm64/boot/dtb
+fi
+
+if [[ -f ${OUT_DIR}/arch/arm64/boot/Image.gz ]]; then
+	rm -fr ${OUT_DIR}/arch/arm64/boot/Image.gz
+elif [[ -f ${OUT_DIR}/arch/arm64/boot/Image ]]; then
+	rm -fr ${OUT_DIR}/arch/arm64/boot/Image
+fi
+
+if [[ -f ${OUT_DIR}/arch/arm64/boot/dtbo.img ]]; then
+	rm -fr ${OUT_DIR}/arch/arm64/boot/dtbo.img
+fi
+
+KBUILD_COMPILER_STRING=$(${HOME}/clang/bin/clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')
+KBUILD_LINKER_STRING=$(${HOME}/clang/bin/ld.lld --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//' | sed 's/(compatible with [^)]*)//')
+export KBUILD_COMPILER_STRING
+export KBUILD_LINKER_STRING
+
+cp -r $HOME/anykernel ./
+
+#
+# Enviromental Variables
+#
+
+DATE=$(date +"%Y-%m-%d-%H%M")
+DEVICE="elish"
 
 # Set our directory
 OUT_DIR=out/
 
-VERSION="IMMENSITY-X-elish-${DATE}"
+VERSION="IMMENSITY-X-${DEVICE^^}-${DATE}"
 
 # Export Zip name
 export ZIPNAME="${VERSION}.zip"
 
-dts_source=arch/arm64/boot/dts/vendor/qcom
+# How much kebabs we need? Kanged from @raphielscape :)
+if [[ -z "${KEBABS}" ]]; then
+    COUNT="$(grep -c '^processor' /proc/cpuinfo)"
+    export KEBABS="$((COUNT + 2))"
+fi
 
+echo "Jobs: ${KEBABS}"
+
+ARGS="ARCH=arm64 \
+O=${OUT_DIR} \
+LLVM=1 \
+CLANG_TRIPLE=aarch64-linux-gnu- \
+CROSS_COMPILE=aarch64-linux-gnu- \
+CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
+-j${KEBABS}"
+
+dts_source=arch/arm64/boot/dts/vendor/qcom
 # Correct panel dimensions on MIUI builds
 function miui_fix_dimens() {
     sed -i 's/<70>/<695>/g' $dts_source/dsi-panel-j3s-37-02-0a-dsc-video.dtsi
@@ -88,69 +132,118 @@ function miui_fix_fod() {
     sed -i 's/\/\/39 01 00 00 00 00 03 51 03 FF/39 01 00 00 00 00 03 51 03 FF/g' $dts_source/dsi-panel-j9-38-0a-0a-fhd-video.dtsi
 }
 
+function enable_lto() {
+    scripts/config --file ${OUT_DIR}/.config \
+        -e LTO_CLANG
+
+    # Make olddefconfig
+    cd ${OUT_DIR} || exit
+    make -j${KEBABS} ${ARGS} olddefconfig
+    cd ../ || exit
+}
+
+function disable_lto() {
+    scripts/config --file ${OUT_DIR}/.config \
+        -d LTO_CLANG
+
+    # Make olddefconfig
+    cd ${OUT_DIR} || exit
+    make -j${KEBABS} ${ARGS} olddefconfig
+    cd ../ || exit
+}
+
+function pack_image_build() {
+    mkdir -p anykernel/kernels/$1
+
+    # Check if the kernel is built
+    if [[ -f ${OUT_DIR}/System.map ]]; then
+        if [[ -f ${OUT_DIR}/arch/arm64/boot/Image.gz ]]; then
+            cp ${OUT_DIR}/arch/arm64/boot/Image.gz anykernel/kernels/$1
+        elif [[ -f ${OUT_DIR}/arch/arm64/boot/Image ]]; then
+            cp ${OUT_DIR}/arch/arm64/boot/Image anykernel/kernels/$1
+        else
+            echo "❎ Kernel compile failed"
+        fi
+    else
+        echo "❎ Kernel compile failed"
+    fi
+
+    cp ${OUT_DIR}/arch/arm64/boot/dtb anykernel/kernels/$1
+    cp ${OUT_DIR}/arch/arm64/boot/dtbo.img anykernel/kernels/$1
+}
+
+START=$(date +"%s")
+
 # Set compiler Path
-    PATH=${HOME}/gas:${HOME}/clang/bin/:$PATH
-    export LD_LIBRARY_PATH=${HOME}/clang/lib64:${LD_LIBRARY_PATH}
+PATH=${HOME}/gas:${HOME}/clang/bin/:$PATH
+export LD_LIBRARY_PATH=${HOME}/clang/lib64:$LD_LIBRARY_PATH
 
 # Make defconfig
-make -j8 ARCH=arm64 O=out/ LLVM=1 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- elish_defconfig
+make -j${KEBABS} ${ARGS} "${DEVICE}"_defconfig
 
 # MIUI Build
 echo "------ Starting MIUI Build ------"
 os=miui
 
-scripts/config --file out/.config \
+# Make defconfig
+make -j${KEBABS} ${ARGS} "${DEVICE}"_defconfig
+
+scripts/config --file ${OUT_DIR}/.config \
     -d LOCALVERSION_AUTO \
     -d TOUCHSCREEN_COMMON \
     --set-str STATIC_USERMODEHELPER_PATH /system/bin/micd \
     -e BOOT_INFO \
     -e BINDER_OPT \
-    -e DEBUG_KERNEL \
     -e IPC_LOGGING \
     -e KPERFEVENTS \
     -e LAST_TOUCH_EVENTS \
     -e MIGT \
     -e MIHW \
     -e MILLET \
-    -e MIUI_DRM_WAKE_OPT \
+    -e MI_DRM_OPT \
     -e MIUI_ZRAM_MEMORY_TRACKING \
     -e MI_RECLAIM \
     -d OSSFOD \
     -e PERF_HUMANTASK \
     -e TASK_DELAY_ACCT
 
+# FIXME: disable LTO on MIUI
+disable_lto
+
+# Make olddefconfig
+cd ${OUT_DIR} || exit
+make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="cache g++" olddefconfig
+cd ../ || exit
 
 miui_fix_dimens
 miui_fix_fps
 miui_fix_dfps
 miui_fix_fod
 
-make -j8 ARCH=arm64 O=out/ LLVM=1 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_COMPAT=arm-linux-gnueabi- 2>&1 | tee build.log
+make -j${KEBABS} ${ARGS} CC="ccache clang" HOSTCC="ccache gcc" HOSTCXX="ccache g++" 2>&1 | tee build.log
 
-find ${OUT_DIR}/arch/arm64/boot/dts/vendor/qcom -name '*.dtb' -exec cat {} + > ${OUT_DIR}/arch/arm64/boot/dtb
+find ${OUT_DIR}/$dts_source -name '*.dtb' -exec cat {} + >${OUT_DIR}/arch/arm64/boot/dtb
 
-mkdir -p $HOME/anykernel/kernels/miui
-# Import Anykernel3 folder
-if [[ -f ${OUT_DIR}/arch/arm64/boot/Image.gz ]]; then
-    cp ${OUT_DIR}/arch/arm64/boot/Image.gz $HOME/anykernel/kernels/miui
-else
-    cp ${OUT_DIR}/arch/arm64/boot/Image $HOME/anykernel/kernels/miui
-fi
-cp ${OUT_DIR}/arch/arm64/boot/dtb $HOME/anykernel/kernels/miui
-cp ${OUT_DIR}/arch/arm64/boot/dtbo.img $HOME/anykernel/kernels/miui
+pack_image_build ${os}
 
-git checkout arch/arm64/boot/dts/vendor &> /dev/null
+git checkout arch/arm64/boot/dts/vendor &>/dev/null
 echo "------ Finishing MIUI Build ------"
 
+END=$(date +"%s")
+DIFF=$((END - START))
 
-cd $HOME/anykernel || exit
+cd anykernel || exit
 zip -r9 "${ZIPNAME}" ./* -x .git .gitignore ./*.zip
 
-CHECKER=$(find ./ -maxdepth 1 -type f -name "${ZIPNAME}" -printf "%s\n")
+CHECKER=$(find ./ -maxdepth 1 -type f -name ${ZIPNAME} -printf "%s\n")
 if (($((CHECKER / 1048576)) > 5)); then
-    echo "✅Kernel compiled successfully in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds for elish"
+    echo "✅ Kernel compiled successfully in $((DIFF / 60)) minute(s) and $((DIFF % 60)) seconds for ${DEVICE}"
 else
-    echo "✅Kernel compile failed"
+    echo "❎️ Kernel compile failed"
 fi
-cd "$(pwd)" || exit
+cd $(pwd) || exit
+
+echo ""
+echo -e $ZIPNAME " is ready!"
+echo ""
 
